### ISSUE TITLE
ادخال خطوط الطول والعرض بشكل يدوي في حال تم رفض صلاحيات الموقع في صفحة اوقات الصلاة

### ISSUE THREAD

**Issue by kemzops** [kanzislam/Kanzislam#3]
يمكن اظهار input لإخال خطوط الطول والعرض في حال رفض المستخدم صلاحية الموقع في صفحة اوقات الصلاة , وبعد الإدخال يتم حفظ المدخلات في التخزين المحلي في المتصفح (LocalStorage) وعمل تحديث للصفحة لتظهر اوقات الصلاة (مع زر لحذف/اعادة ادخال) مثال بسيط:

```js
/* FOR TESTING */
localStorage.setItem("latitude", 32.22111);
localStorage.setItem("longitude", 35.25444);

const latitude = localStorage.getItem("latitude");
const longitude = localStorage.getItem("longitude");

const prayerData = prayerTimes({
    Calculation: "UmmAlQura",
    latitude: latitude,
    longitude: longitude,
    Madhab: "Shafi",
    Shafaq: "Ahmer",
});
```

**Comment by kemzops** [comment]
بعد تطبيق المثال تظهر اوقات الصلاة بشكل طبيعي وصحيح, دون الحاجة لصلاحية الموقع.

![image](https://github.com/kanzislam/Kanzislam/assets/52936496/c22f60a1-d38d-4714-81e6-11255434e172)

**Comment by kemzops** [comment]
@rn0x بحاجة لتعديل على تصميم الواجهة , اذا بتقدر تشتغل عليها ياريت وجزاك الله خير.

**Comment by kemzops** [comment]
وطبعا هذا الاقتراح بسبب المتصفح الي استخدمه ما بيدعم صلاحية الموقع (LibreWolf)... بدل من شاشة التحذير:

![image](https://github.com/kanzislam/Kanzislam/assets/52936496/1570c09d-4d54-4671-85e8-4008e16a1bc9)

**Comment by rn0x** [comment]
يعطيك العافيه على الاقتراح تم اضافة صفحة للادخال اليدوي (خطوط الطول والعرض والمنطقة الزمنية والمذهب وطريقة الحساب) 8cf0e0a3f587e56dea8790ca347ab0ad0b6718e2

<img width="917" alt="brave_NWw9lPXvlp" src="https://github.com/kanzislam/Kanzislam/assets/76129163/b58eaa08-920d-42a5-90b8-8d66c89c5292">


<img width="426" alt="explorer_D7VTHopRaL" src="https://github.com/kanzislam/Kanzislam/assets/76129163/875216e8-527d-4184-9365-238c28dc7afc">

**Comment by kemzops** [comment]
جزاك الله خير , يعطيك العافية !!.
